//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.18 at 04:30:13 PM BST 
//


package com.glookast.commons.capture.info;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PixelFormat.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="PixelFormat">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="UNKNOWN"/>
 *     &lt;enumeration value="UYVY"/>
 *     &lt;enumeration value="V210"/>
 *     &lt;enumeration value="RGB24"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "PixelFormat", namespace = "http://capture-info.commons.glookast.com")
@XmlEnum
public enum PixelFormat {

    UNKNOWN("UNKNOWN"),
    UYVY("UYVY"),
    @XmlEnumValue("V210")
    V_210("V210"),
    @XmlEnumValue("RGB24")
    RGB_24("RGB24");
    private final String value;

    PixelFormat(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static PixelFormat fromValue(String v) {
        for (PixelFormat c: PixelFormat.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
