//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.18 at 04:30:13 PM BST 
//


package com.glookast.commons.capture.info;

import com.glookast.commons.base.Rational;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SignalFormat complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SignalFormat">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="frameRate" type="{http://base.commons.glookast.com}Rational"/>
 *         &lt;element name="picture" type="{http://capture-info.commons.glookast.com}PictureFormat"/>
 *         &lt;element name="sound" type="{http://capture-info.commons.glookast.com}SoundFormat"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SignalFormat", namespace = "http://capture-info.commons.glookast.com", propOrder = {
    "frameRate",
    "picture",
    "sound"
})
public class SignalFormat {

    protected Rational frameRate;
    protected PictureFormat picture;
    protected SoundFormat sound;

    public SignalFormat()
    {
    }

    public SignalFormat(Rational frameRate, PictureFormat picture, SoundFormat sound)
    {
        this.frameRate = frameRate;
        this.picture = picture;
        this.sound = sound;
    }

    /**
     * Gets the value of the frameRate property.
     * 
     * @return
     *     possible object is
     *     {@link Rational }
     *     
     */
    public Rational getFrameRate() {
        return frameRate;
    }

    /**
     * Sets the value of the frameRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link Rational }
     *     
     */
    public void setFrameRate(Rational value) {
        this.frameRate = value;
    }

    /**
     * Gets the value of the picture property.
     * 
     * @return
     *     possible object is
     *     {@link PictureFormat }
     *     
     */
    public PictureFormat getPicture() {
        return picture;
    }

    /**
     * Sets the value of the picture property.
     * 
     * @param value
     *     allowed object is
     *     {@link PictureFormat }
     *     
     */
    public void setPicture(PictureFormat value) {
        this.picture = value;
    }

    /**
     * Gets the value of the sound property.
     * 
     * @return
     *     possible object is
     *     {@link SoundFormat }
     *     
     */
    public SoundFormat getSound() {
        return sound;
    }

    /**
     * Sets the value of the sound property.
     * 
     * @param value
     *     allowed object is
     *     {@link SoundFormat }
     *     
     */
    public void setSound(SoundFormat value) {
        this.sound = value;
    }

    @Override
    public String toString()
    {
        return "SignalFormat{" +
                "frameRate=" + frameRate +
                ", picture=" + picture +
                ", sound=" + sound +
                '}';
    }
}
