//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.18 at 04:30:13 PM BST 
//


package com.glookast.commons.capture.info;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SoundFormat complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SoundFormat">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="channelCount" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="sampleSize" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="samplingRate" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SoundFormat", namespace = "http://capture-info.commons.glookast.com", propOrder = {
    "channelCount",
    "sampleSize",
    "samplingRate"
})
public class SoundFormat {

    protected int channelCount;
    protected int sampleSize;
    protected int samplingRate;

    public SoundFormat()
    {
    }

    public SoundFormat(int channelCount, int sampleSize, int samplingRate)
    {
        this.channelCount = channelCount;
        this.sampleSize = sampleSize;
        this.samplingRate = samplingRate;
    }

    /**
     * Gets the value of the channelCount property.
     * 
     */
    public int getChannelCount() {
        return channelCount;
    }

    /**
     * Sets the value of the channelCount property.
     * 
     */
    public void setChannelCount(int value) {
        this.channelCount = value;
    }

    /**
     * Gets the value of the sampleSize property.
     * 
     */
    public int getSampleSize() {
        return sampleSize;
    }

    /**
     * Sets the value of the sampleSize property.
     * 
     */
    public void setSampleSize(int value) {
        this.sampleSize = value;
    }

    /**
     * Gets the value of the samplingRate property.
     * 
     */
    public int getSamplingRate() {
        return samplingRate;
    }

    /**
     * Sets the value of the samplingRate property.
     * 
     */
    public void setSamplingRate(int value) {
        this.samplingRate = value;
    }

    @Override
    public String toString()
    {
        return "SoundFormat{" +
                "channelCount=" + channelCount +
                ", sampleSize=" + sampleSize +
                ", samplingRate=" + samplingRate +
                '}';
    }
}
