//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.18 at 04:30:13 PM BST 
//


package com.glookast.commons.capture.info;

import com.glookast.commons.timecode.Timecode;
import com.glookast.commons.timecode.XmlAdapterTimecode;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for TimecodeCollection complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TimecodeCollection">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ltc" type="{http://timecode.commons.glookast.com}Timecode"/>
 *         &lt;element name="vitc" type="{http://timecode.commons.glookast.com}Timecode"/>
 *         &lt;element name="tod" type="{http://timecode.commons.glookast.com}Timecode"/>
 *         &lt;element name="rs422" type="{http://timecode.commons.glookast.com}Timecode"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TimecodeCollection", namespace = "http://capture-info.commons.glookast.com", propOrder = {
    "ltc",
    "vitc",
    "tod",
    "rs422"
})
public class TimecodeCollection {

    @XmlElement(type = String.class)
    @XmlJavaTypeAdapter(XmlAdapterTimecode.class)
    protected Timecode ltc;
    @XmlElement(type = String.class)
    @XmlJavaTypeAdapter(XmlAdapterTimecode.class)
    protected Timecode vitc;
    @XmlElement(type = String.class)
    @XmlJavaTypeAdapter(XmlAdapterTimecode.class)
    protected Timecode tod;
    @XmlElement(type = String.class)
    @XmlJavaTypeAdapter(XmlAdapterTimecode.class)
    protected Timecode rs422;

    public TimecodeCollection()
    {
    }

    public TimecodeCollection(Timecode ltc, Timecode vitc, Timecode tod, Timecode rs422)
    {
        this.ltc = ltc;
        this.vitc = vitc;
        this.tod = tod;
        this.rs422 = rs422;
    }

    /**
     * Gets the value of the ltc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Timecode getLtc() {
        return ltc;
    }

    /**
     * Sets the value of the ltc property.
     * 
     * @param value
     *     allowed object is
     *     {@link Timecode }
     *     
     */
    public void setLtc(Timecode value) {
        this.ltc = value;
    }

    /**
     * Gets the value of the vitc property.
     * 
     * @return
     *     possible object is
     *     {@link Timecode }
     *     
     */
    public Timecode getVitc() {
        return vitc;
    }

    /**
     * Sets the value of the vitc property.
     * 
     * @param value
     *     allowed object is
     *     {@link Timecode }
     *     
     */
    public void setVitc(Timecode value) {
        this.vitc = value;
    }

    /**
     * Gets the value of the tod property.
     * 
     * @return
     *     possible object is
     *     {@link Timecode }
     *     
     */
    public Timecode getTod() {
        return tod;
    }

    /**
     * Sets the value of the tod property.
     * 
     * @param value
     *     allowed object is
     *     {@link Timecode }
     *     
     */
    public void setTod(Timecode value) {
        this.tod = value;
    }

    /**
     * Gets the value of the rs422 property.
     * 
     * @return
     *     possible object is
     *     {@link Timecode }
     *     
     */
    public Timecode getRs422() {
        return rs422;
    }

    /**
     * Sets the value of the rs422 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Timecode }
     *     
     */
    public void setRs422(Timecode value) {
        this.rs422 = value;
    }

    @Override
    public String toString()
    {
        return "TimecodeCollection{" +
                "ltc='" + ltc + '\'' +
                ", vitc='" + vitc + '\'' +
                ", tod='" + tod + '\'' +
                ", rs422='" + rs422 + '\'' +
                '}';
    }
}
